# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-04 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=100, verbose_name='URL')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('content', models.TextField(blank=True, verbose_name='content')),
                ('template_name', models.CharField(blank=True, help_text="Example: 'pages/contact_page.html'. If this isn't provided, the system will use 'pages/default.html'.", max_length=70, verbose_name='template name')),
                ('publish', models.BooleanField(help_text='If this is checked, the page will be included in the site menus.', verbose_name='publish')),
                ('index', models.IntegerField(default=0, help_text='Used to order pages in the menu', verbose_name='ordering index')),
                ('group_required', models.ForeignKey(blank=True, help_text='This page will only be visible to members of this group, leave blank to allow anyone to access.', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('parent', models.ForeignKey(blank=True, help_text='Leave blank for a top level menu entry.  Top level entries that have sub-pages should be empty as they will not be linked in the menu.', null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Page')),
            ],
            options={
                'ordering': ('url', 'index'),
                'verbose_name': 'page',
                'verbose_name_plural': 'pages',
            },
        ),
    ]
